# https://raw.githubusercontent.com/bitnami/containers/main/bitnami/magento/docker-compose.yml

# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: ${MAGENTO_USER}
      MYSQL_PASSWORD: ${MAGENTO_PW}
      MYSQL_DATABASE: ${MAGENTO_DB}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - m2net
    ports:
      - "3306:3306"

  # we replace this with `mysql`
  # mariadb:
  #   image: docker.io/bitnami/mariadb:10.6
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - MARIADB_USER=dbUser
  #     - MARIADB_DATABASE=magentoDB
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - 'mariadb_data:/bitnami/mariadb'

  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
    networks:
      - m2net

  magento:
    image: docker.io/bitnami/magento:2
    ports:
      - '80:8080'
      - '443:8443'
    networks:
      - m2net



    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mysql
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=${MAGENTO_USER}
      - MAGENTO_DATABASE_PASSWORD=${MAGENTO_PW}
      - MAGENTO_DATABASE_NAME=${MAGENTO_DB}

      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200

      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      # - mariadb
      - mysql
      - elasticsearch

networks:
  m2net:

volumes:
  # we replace this with `mysql`
  # mariadb_data:
  #   driver: local
  mysql_data:
    driver: local
  elasticsearch_data:
    driver: local
  magento_data:
    driver: local